PAGES = [
    "geracao_jogos",
    "conferir_jogos",
    "reconciliacao_operacional",
    "estatisticas_historicas",
    "historical_intelligence",
    "analytics_intelligence",
    "ml_intelligence",
    "jogo_expandido_experimental",
    "backtesting",
    "calibracao_experimental",
    "benchmark_cientifico",
    "historico_experimental",
    "relatorios",
    "ml_governance",
    "observability",
    "workflows",
    "reports_engine",
]

LABELS = {
    "geracao_jogos": "Gerar Jogos",
    "conferir_jogos": "Jogos Passados",
    "reconciliacao_operacional": "Simular Resultado",
    "estatisticas_historicas": "Resultados Passados",
    "historical_intelligence": "Historico",
    "analytics_intelligence": "Analises",
    "ml_intelligence": "ML",
    "jogo_expandido_experimental": "Jogo Expandido",
    "backtesting": "Backtesting",
    "calibracao_experimental": "Ajustes Operacionais",
    "benchmark_cientifico": "Comparativos Cientificos",
    "historico_experimental": "Historico Operacional",
    "relatorios": "Analiticas Persistidas",
    "ml_governance": "Governanca ML",
    "observability": "Monitoramento",
    "workflows": "Automacao",
    "reports_engine": "Relatorios Tecnicos",
}
