# C:\Projetos\LotoIA\dashboard\labels.py
PAGES = [
    "geracao_jogos",
    "conferir_jogos",
    "estatisticas_historicas",
    "historical_intelligence",
    "analytics_intelligence",
    "ml_intelligence",
    "jogo_expandido_experimental",
    "backtesting",
    "calibracao_experimental",
    "benchmark_cientifico",
    "historico_experimental",
    "relatorios",
    "ml_governance",
    "observability",
    "workflows",
    "reports_engine",
]

LABELS = {
    "geracao_jogos": "Gerar Jogos",
    "conferir_jogos": "Conferir Jogos",
    "estatisticas_historicas": "Resultados Passados",
    "historical_intelligence": "Historico",
    "analytics_intelligence": "Analises",
    "ml_intelligence": "ML",
    "jogo_expandido_experimental": "Jogo Expandido",
    "backtesting": "Testes Operacionais",
    "calibracao_experimental": "Estrategias Operacionais",
    "benchmark_cientifico": "Comparativos Operacionais",
    "historico_experimental": "Testes Operacionais",
    "relatorios": "Analiticas Persistidas",
    "ml_governance": "Governanca ML",
    "observability": "Monitoramento",
    "workflows": "Automacao",
    "reports_engine": "Relatorios",
}
