# C:\Projetos\LotoIA\dashboard\labels.py
PAGES = [
    "geracao_jogos",
    "conferir_jogos",
    "estatisticas_historicas",
    "historical_intelligence",
    "analytics_intelligence",
    "ml_intelligence",
    "jogo_expandido_experimental",
    "backtesting",
    "calibracao_experimental",
    "benchmark_cientifico",
    "historico_experimental",
    "relatorios",
    "ml_governance",
    "observability",
    "reports_engine",
]

LABELS = {
    "geracao_jogos": "Criar Jogos",
    "conferir_jogos": "Conferir Jogos",
    "estatisticas_historicas": "Resultados Passados",
    "historical_intelligence": "Historical Intelligence",
    "analytics_intelligence": "Analytics Intelligence",
    "ml_intelligence": "ML Intelligence",
    "jogo_expandido_experimental": "Jogo Expandido (Experimental)",
    "backtesting": "Testar Estratégia",
    "calibracao_experimental": "Ajustar Estratégia",
    "benchmark_cientifico": "Comparar Métodos",
    "historico_experimental": "Meus Testes",
    "relatorios": "Relatórios",
    "ml_governance": "ML Governance",
    "observability": "Observability",
    "reports_engine": "Reports Engine",
}
