from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "InterpretableLinearScoreML",
    "ScoreMLResult",
    "attach_score_ml",
    "calibrate_linear_score_ml",
    "default_calibration_config",
    "extract_score_ml_features",
    "ensure_calibration",
    "ml_heartbeat",
    "migrate_score_ml_snapshot",
    "activate_score_ml_runtime",
    "DEFAULT_ML_EXPERIMENT_TRACKING_DIR",
    "DEFAULT_ML_EXPERIMENT_TRACKING_REGISTRY",
    "MLExperimentTrackingResult",
    "track_ml_experiment",
    "DEFAULT_ML_MODEL_REGISTRY_DIR",
    "DEFAULT_ML_MODEL_REGISTRY_PATH",
    "MLModelRegistryResult",
    "activate_model_version",
    "register_model_version",
    "rollback_model_version",
    "DEFAULT_ML_FEATURE_LINEAGE_DIR",
    "DEFAULT_ML_FEATURE_LINEAGE_REGISTRY",
    "MLFeatureLineageResult",
    "build_feature_lineage",
    "DEFAULT_ML_CALIBRATION_GOVERNANCE_DIR",
    "DEFAULT_ML_CALIBRATION_GOVERNANCE_REGISTRY",
    "MLCalibrationGovernanceResult",
    "register_calibration_snapshot",
    "DEFAULT_ML_DRIFT_DETECTION_DIR",
    "DEFAULT_ML_DRIFT_DETECTION_REGISTRY",
    "MLDriftDetectionResult",
    "detect_ml_drift",
    "DEFAULT_ML_EXPLAINABILITY_DIR",
    "DEFAULT_ML_EXPLAINABILITY_REGISTRY",
    "MLExplainabilityResult",
    "explain_score_ml_game",
    "MLRuntimeIsolationContract",
    "describe_ml_runtime_isolation",
    "get_isolated_ml_runtime_state",
    "DEFAULT_WALK_FORWARD_VALIDATION_DIR",
    "DEFAULT_WALK_FORWARD_VALIDATION_ID",
    "WalkForwardValidationResult",
    "build_walk_forward_validation_report",
    "score_ml_games",
    "supervised_rerank_games",
    "run_walk_forward_validation",
]

_EXPORTS: dict[str, tuple[str, str]] = {
    "InterpretableLinearScoreML": ("lotoia.ml.score_ml", "InterpretableLinearScoreML"),
    "ScoreMLResult": ("lotoia.ml.score_ml", "ScoreMLResult"),
    "attach_score_ml": ("lotoia.ml.score_ml", "attach_score_ml"),
    "calibrate_linear_score_ml": ("lotoia.ml.score_ml", "calibrate_linear_score_ml"),
    "default_calibration_config": ("lotoia.ml.score_ml", "default_calibration_config"),
    "extract_score_ml_features": ("lotoia.ml.score_ml", "extract_score_ml_features"),
    "ensure_calibration": ("lotoia.ml.score_ml", "ensure_calibration"),
    "ml_heartbeat": ("lotoia.ml.score_ml", "ml_heartbeat"),
    "migrate_score_ml_snapshot": ("lotoia.ml.score_ml", "migrate_score_ml_snapshot"),
    "score_ml_games": ("lotoia.ml.score_ml", "score_ml_games"),
    "supervised_rerank_games": ("lotoia.ml.score_ml", "supervised_rerank_games"),
    "activate_score_ml_runtime": ("lotoia.ml.governance", "activate_score_ml_runtime"),
    "DEFAULT_ML_EXPERIMENT_TRACKING_DIR": ("lotoia.ml.experiment_tracking", "DEFAULT_ML_EXPERIMENT_TRACKING_DIR"),
    "DEFAULT_ML_EXPERIMENT_TRACKING_REGISTRY": ("lotoia.ml.experiment_tracking", "DEFAULT_ML_EXPERIMENT_TRACKING_REGISTRY"),
    "MLExperimentTrackingResult": ("lotoia.ml.experiment_tracking", "MLExperimentTrackingResult"),
    "track_ml_experiment": ("lotoia.ml.experiment_tracking", "track_ml_experiment"),
    "DEFAULT_ML_MODEL_REGISTRY_DIR": ("lotoia.ml.model_registry", "DEFAULT_ML_MODEL_REGISTRY_DIR"),
    "DEFAULT_ML_MODEL_REGISTRY_PATH": ("lotoia.ml.model_registry", "DEFAULT_ML_MODEL_REGISTRY_PATH"),
    "MLModelRegistryResult": ("lotoia.ml.model_registry", "MLModelRegistryResult"),
    "activate_model_version": ("lotoia.ml.model_registry", "activate_model_version"),
    "register_model_version": ("lotoia.ml.model_registry", "register_model_version"),
    "rollback_model_version": ("lotoia.ml.model_registry", "rollback_model_version"),
    "DEFAULT_ML_FEATURE_LINEAGE_DIR": ("lotoia.ml.feature_lineage", "DEFAULT_ML_FEATURE_LINEAGE_DIR"),
    "DEFAULT_ML_FEATURE_LINEAGE_REGISTRY": ("lotoia.ml.feature_lineage", "DEFAULT_ML_FEATURE_LINEAGE_REGISTRY"),
    "MLFeatureLineageResult": ("lotoia.ml.feature_lineage", "MLFeatureLineageResult"),
    "build_feature_lineage": ("lotoia.ml.feature_lineage", "build_feature_lineage"),
    "DEFAULT_ML_CALIBRATION_GOVERNANCE_DIR": ("lotoia.ml.calibration_governance", "DEFAULT_ML_CALIBRATION_GOVERNANCE_DIR"),
    "DEFAULT_ML_CALIBRATION_GOVERNANCE_REGISTRY": ("lotoia.ml.calibration_governance", "DEFAULT_ML_CALIBRATION_GOVERNANCE_REGISTRY"),
    "MLCalibrationGovernanceResult": ("lotoia.ml.calibration_governance", "MLCalibrationGovernanceResult"),
    "register_calibration_snapshot": ("lotoia.ml.calibration_governance", "register_calibration_snapshot"),
    "DEFAULT_ML_DRIFT_DETECTION_DIR": ("lotoia.ml.drift_detection", "DEFAULT_ML_DRIFT_DETECTION_DIR"),
    "DEFAULT_ML_DRIFT_DETECTION_REGISTRY": ("lotoia.ml.drift_detection", "DEFAULT_ML_DRIFT_DETECTION_REGISTRY"),
    "MLDriftDetectionResult": ("lotoia.ml.drift_detection", "MLDriftDetectionResult"),
    "detect_ml_drift": ("lotoia.ml.drift_detection", "detect_ml_drift"),
    "DEFAULT_ML_EXPLAINABILITY_DIR": ("lotoia.ml.explainability", "DEFAULT_ML_EXPLAINABILITY_DIR"),
    "DEFAULT_ML_EXPLAINABILITY_REGISTRY": ("lotoia.ml.explainability", "DEFAULT_ML_EXPLAINABILITY_REGISTRY"),
    "MLExplainabilityResult": ("lotoia.ml.explainability", "MLExplainabilityResult"),
    "explain_score_ml_game": ("lotoia.ml.explainability", "explain_score_ml_game"),
    "MLRuntimeIsolationContract": ("lotoia.ml.runtime_isolation", "MLRuntimeIsolationContract"),
    "describe_ml_runtime_isolation": ("lotoia.ml.runtime_isolation", "describe_ml_runtime_isolation"),
    "get_isolated_ml_runtime_state": ("lotoia.ml.runtime_isolation", "get_isolated_ml_runtime_state"),
    "DEFAULT_WALK_FORWARD_VALIDATION_DIR": ("lotoia.ml.walk_forward_validation", "DEFAULT_WALK_FORWARD_VALIDATION_DIR"),
    "DEFAULT_WALK_FORWARD_VALIDATION_ID": ("lotoia.ml.walk_forward_validation", "DEFAULT_WALK_FORWARD_VALIDATION_ID"),
    "WalkForwardValidationResult": ("lotoia.ml.walk_forward_validation", "WalkForwardValidationResult"),
    "build_walk_forward_validation_report": ("lotoia.ml.walk_forward_validation", "build_walk_forward_validation_report"),
    "run_walk_forward_validation": ("lotoia.ml.walk_forward_validation", "run_walk_forward_validation"),
}


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(name)
    module_name, attr_name = _EXPORTS[name]
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
